const $ = (id) => document.getElementById(id);
const APP_VERSION='20260729-tool-v3b';
const RECENT_KEY='kpa.v3.recent';
const RESULT_KEY='kpa.v3.result';
const RUN_KEY='kpa.v3.run';
const MAX_RECENT=100;
const SAMPLE_LIMIT=4;
const state={data:null,busy:false,runToken:0};

function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeUrl(v=''){try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function host(v=''){try{return new URL(v).hostname.replace(/^www\./,'')}catch{return v}}
function clean(v='',max=180){return String(v||'').replace(/\s+/g,' ').trim().slice(0,max)}
function roleKo(role=''){const k=String(role).toLowerCase();if(k.includes('partnership'))return'파트너십 책임자';if(k.includes('business development'))return'사업개발 책임자';if(k.includes('sales'))return'영업 책임자';if(k.includes('growth'))return'성장 책임자';if(k.includes('apac')||k.includes('asia'))return'APAC 책임자';if(k.includes('founder'))return'창업자';if(k.includes('ceo'))return'대표';return role||'GTM 책임자'}
function readRecent(){try{const v=JSON.parse(localStorage.getItem(RECENT_KEY)||'[]');return Array.isArray(v)?v.slice(0,MAX_RECENT):[]}catch{return[]}}
function saveRecent(names=[]){const seen=new Set();const merged=[...names,...readRecent()].map(String).map(x=>x.trim()).filter(Boolean).filter(x=>{const k=x.toLowerCase();if(seen.has(k))return false;seen.add(k);return true});localStorage.setItem(RECENT_KEY,JSON.stringify(merged.slice(0,MAX_RECENT)))}
async function readJson(r){const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{throw new Error(`응답 형식 오류 (HTTP ${r.status})`)}if(!r.ok)throw new Error(`${data.error||`HTTP ${r.status}`}${data.hint?` · ${data.hint}`:''}`);return data}
async function post(url,payload,timeout=120000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await readJson(await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store',signal:c.signal}))}catch(e){if(e?.name==='AbortError')throw new Error('처리가 너무 오래 걸려 중단됐습니다.');throw e}finally{clearTimeout(t)}}

async function health(){try{const d=await readJson(await fetch(`/api/health?t=${Date.now()}`,{cache:'no-store'}));const ok=Boolean(d.aiConnected&&d.tavilyConfigured);$('apiStatus').className=`status ${ok?'ok':'bad'}`;$('apiStatus').innerHTML=`<span class="dot"></span><span>${ok?'정상':'확인 필요'}</span>`;return ok}catch{$('apiStatus').className='status bad';$('apiStatus').innerHTML='<span class="dot"></span><span>오류</span>';return false}}
async function diagnostics(){const panel=$('diagPanel');panel.classList.remove('hidden');panel.innerHTML='<div class="diag">확인 중…</div>';try{const h=await readJson(await fetch(`/api/health?t=${Date.now()}`,{cache:'no-store'}));const line=(name,ok,detail)=>`<div class="diag-row"><b class="${ok?'diag-ok':'diag-bad'}">${ok?'✓':'✕'}</b><span>${escapeHtml(name)} · ${escapeHtml(detail)}</span></div>`;panel.innerHTML=`<div class="diag">${line('웹 검색',h.tavilyConfigured,h.tavilyConfigured?'정상':'설정 필요')}${line('AI 분석',h.aiConnected,h.aiModel||'연결 필요')}${line('연락처 탐색',true,'공개 웹/연결된 공급자')}</div>`}catch(e){panel.innerHTML=`<div class="diag">${escapeHtml(e.message)}</div>`}}

function setBusy(on,text=''){state.busy=on;$('runBtn').disabled=on;$('runBtn').textContent=on?(text||'찾는 중…'):'새 후보 찾기'}
function showLoading(title,sub){$('content').innerHTML=`<div class="loading"><strong>${escapeHtml(title)}</strong><span>${escapeHtml(sub)}</span></div>`;$('summary').innerHTML=''}
function showError(msg){$('content').innerHTML=`<div class="error">${escapeHtml(msg)}</div>`;$('summary').innerHTML=''}
function sampleProspects(lead){return Array.isArray(lead?.sample?.prospects)?lead.sample.prospects.slice(0,3):[]}
function englishMail(lead){const c=lead.contact||{};const first=String(c.name||'').trim().split(/\s+/)[0];const hello=first?`Hi ${first},`:'Hi,';const accounts=sampleProspects(lead);const lines=accounts.map((p,i)=>`${i+1}. ${p.company_en||p.company} — ${p.recommended_role_en||'Business leader'}${p.buying_signal_en?`: ${clean(p.buying_signal_en,150)}`:''}`).join('\n');const signal=lead.signal_title_en?clean(lead.signal_title_en,180):'recent APAC expansion activity';if(!accounts.length)return `${hello}\n\nI noticed ${lead.company}'s ${signal}.\n\nI help overseas B2B software companies test Korea before committing local headcount. I can map a small set of Korean accounts, buyer roles, and the public signals behind them.\n\nWorth seeing a quick Korea market sample?`;return `${hello}\n\nI noticed ${lead.company}'s ${signal}.\n\nI mapped ${accounts.length} Korean accounts I would test first:\n\n${lines}\n\nThese are based on current public buying signals rather than a generic company list. I can verify the buyers, localize the outreach, and test demand before you commit local headcount.\n\nWorth a quick Korea pilot?`}
function gmailUrl(lead){const email=lead?.contact?.email;if(!email)return'';const n=sampleProspects(lead).length;const subject=n?`${n} Korea accounts worth testing for ${lead.company}`:`Korea market test for ${lead.company}`;return`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(email)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(lead.outreach_en||englishMail(lead))}`}
function evidenceLinks(lead){return(Array.isArray(lead.evidence)?lead.evidence:[]).slice(0,3).map((e,i)=>{const u=safeUrl(e?.url);return u?`<a href="${escapeHtml(u)}" target="_blank" rel="noopener noreferrer">근거 ${i+1}</a>`:''}).join('')}
function sampleState(lead){if(sampleProspects(lead).length)return'';if(lead.sample_status==='failed')return'강한 후보 없음';if(lead.sample_status==='skipped')return'상위 4곳만 자동 검증';return'검증 중…'}

function render(){const leads=state.data?.leads||[];if(!leads.length){$('content').innerHTML='<div class="empty"><strong>아직 후보가 없습니다.</strong><span>새 후보 찾기를 눌러 시작하세요.</span></div>';$('summary').innerHTML='';return}const contactCount=leads.filter(x=>x.contact?.email).length;const sampleCount=leads.filter(x=>sampleProspects(x).length).length;$('summary').innerHTML=`<strong>${leads.length}개 후보</strong><span>연락처 ${contactCount}</span><span>한국 샘플 ${sampleCount}</span><span>점수순</span>`;$('content').innerHTML=`<table class="lead-table"><thead><tr><th>#</th><th>회사</th><th>점수</th><th>왜 지금</th><th>담당자</th><th>한국 테스트 계정</th><th></th></tr></thead><tbody>${leads.map((lead,i)=>{const c=lead.contact||{};const samples=sampleProspects(lead);const mail=gmailUrl(lead);const detailId=`detail-${i}`;return`<tr class="data-row"><td class="rank">${i+1}</td><td class="company"><strong>${escapeHtml(lead.company)}</strong>${lead.url?`<a href="${escapeHtml(safeUrl(lead.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(host(lead.url))}</a>`:''}<p>${escapeHtml(lead.product_summary||'')}</p></td><td><span class="score">${Math.round(Number(lead.priority_score)||0)}</span></td><td class="signal"><strong>${escapeHtml(lead.why_now||lead.signal_title||'')}</strong><small>${escapeHtml(lead.korea_gap||'한국 조직 공백 확인')}</small></td><td class="contact">${c.email?`<strong>${escapeHtml(c.name||roleKo(lead.recommended_role))}</strong><span>${escapeHtml(c.title||roleKo(lead.recommended_role))}</span><a href="mailto:${escapeHtml(c.email)}">${escapeHtml(c.email)}</a>`:`<strong>${escapeHtml(roleKo(lead.recommended_role))}</strong><small class="pending">${lead.contact_status==='failed'?'연락처 미확보':'연락처 탐색 중…'}</small>`}</td><td>${samples.length?`<div class="sample-badges">${samples.map(p=>`<span class="sample-badge">${escapeHtml(p.company)}</span>`).join('')}</div>`:`<span class="sample-state">${escapeHtml(sampleState(lead))}</span>`}</td><td><div class="actions">${mail?`<a class="mail-btn" href="${escapeHtml(mail)}" target="_blank" rel="noopener noreferrer">메일</a>`:''}<button class="detail-btn" data-detail="${detailId}">상세</button></div></td></tr><tr class="detail-row"><td colspan="7"><div class="detail" id="${detailId}"><section><h4>한국 기회</h4><p>${escapeHtml(lead.korea_opportunity||lead.korea_gap||'')}</p></section><section><h4>근거</h4><div class="evidence">${evidenceLinks(lead)}</div></section>${samples.length?`<section><h4>한국 테스트 계정</h4><p>${samples.map((p,idx)=>`${idx+1}. ${p.company} · ${p.buying_signal||p.why_fit||''}`).map(escapeHtml).join('<br>')}</p></section>`:''}${c.email?`<section class="mail-preview"><h4>보낼 메일 · 영어만 사용</h4><pre>${escapeHtml(lead.outreach_en||englishMail(lead))}</pre></section>`:''}</div></td></tr>`}).join('')}</tbody></table>`;document.querySelectorAll('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>$(btn.dataset.detail)?.classList.toggle('open')))}

function updateLead(index,patch,token){if(token!==undefined&&token!==state.runToken)return;if(!state.data?.leads?.[index])return;state.data.leads[index]={...state.data.leads[index],...patch};localStorage.setItem(RESULT_KEY,JSON.stringify(state.data));render()}
async function enrichLead(lead,index,token){const tasks=[];tasks.push(post('/api/contact',{url:lead.url,recommendedRole:lead.recommended_role},45000).then(d=>updateLead(index,{contact:d.contact||null,contact_status:d.contact?.email?'found':'failed'},token)).catch(()=>updateLead(index,{contact_status:'failed'},token)));if(index<SAMPLE_LIMIT){tasks.push(post('/api/analyze-v2',{clientUrl:lead.url,productHint:lead.product_summary||'',targetNotes:'유명 대기업이 아니라 이 제품을 지금 실제로 살 이유가 있고 최근 12개월 공개 구매 신호가 있는 한국 B2B 기업만.'},100000).then(sample=>updateLead(index,{sample,sample_status:'ready'},token)).catch(()=>updateLead(index,{sample_status:'failed'},token)))}await Promise.allSettled(tasks)}

async function run(){const token=++state.runToken;setBusy(true);showLoading('후보를 찾는 중입니다.','후보가 나오면 먼저 보여주고 연락처와 한국 계정은 뒤에서 병렬로 채웁니다.');try{if(!await health())throw new Error('검색 또는 AI 연결 상태를 확인해주세요.');const run=Number(localStorage.getItem(RUN_KEY)||'0')+1;localStorage.setItem(RUN_KEY,String(run));const d=await post('/api/discover-v2',{focus:'',excludeCompanies:readRecent(),searchVariant:`${new Date().toISOString().slice(0,10)}-${run}`},120000);if(token!==state.runToken)return;const leads=(Array.isArray(d?.leads)?d.leads:[]).slice(0,8).map((x,i)=>({...x,contact:null,contact_status:'pending',sample:null,sample_status:i<SAMPLE_LIMIT?'pending':'skipped'}));if(!leads.length)throw new Error('이번 검색에서는 기준을 통과한 후보가 없었습니다. 다시 누르면 다른 탐색군을 봅니다.');state.data={generated_at:new Date().toISOString(),leads,meta:d.meta||{}};saveRecent(leads.map(x=>x.company));localStorage.setItem(RESULT_KEY,JSON.stringify(state.data));render();setBusy(true,'보강 중…');await Promise.allSettled(leads.map((lead,i)=>enrichLead(lead,i,token)));if(token===state.runToken)setBusy(false)}catch(e){if(token===state.runToken){showError(e.message||'후보 탐색에 실패했습니다.');setBusy(false)}}}

$('runBtn').addEventListener('click',run);$('diagBtn').addEventListener('click',()=>{$('diagPanel').classList.toggle('hidden');if(!$('diagPanel').classList.contains('hidden'))diagnostics()});
if(localStorage.getItem('kpa.v3.version')!==APP_VERSION){localStorage.removeItem(RESULT_KEY);localStorage.setItem('kpa.v3.version',APP_VERSION)}
try{const saved=JSON.parse(localStorage.getItem(RESULT_KEY)||'null');if(saved?.leads?.length){state.data=saved;render()}else render()}catch{render()}
health();