const $ = (id) => document.getElementById(id);
const APP_VERSION = '20260727-9';
const state = { workflow: 'sales', salesData: null, deliveryData: null, deliveryTab: 'prospects' };

if (localStorage.getItem('kpa.app.version') !== APP_VERSION) {
  ['kpa.sales.result','kpa.sales.form','kpa.delivery.result'].forEach(k => localStorage.removeItem(k));
  localStorage.setItem('kpa.app.version', APP_VERSION);
}

function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function safeUrl(v=''){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function host(v=''){try{return new URL(v).hostname.replace(/^www\./,'')}catch{return v}}
function csvCell(v){const s=Array.isArray(v)?v.join(' | '):String(v??'');return `"${s.replace(/"/g,'""')}"`}
function download(name,type,content){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function googleSearchUrl(q=''){return `https://www.google.com/search?q=${encodeURIComponent(q)}`}
async function copyText(text,btn){await navigator.clipboard.writeText(text||'');const old=btn.textContent;btn.textContent='복사됨';setTimeout(()=>btn.textContent=old,900)}

async function readJsonResponse(response){const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{throw new Error(`API 응답 형식 오류 (HTTP ${response.status})`)}if(!response.ok)throw new Error(`${data?.error||`HTTP ${response.status}`}${data?.hint?` · ${data.hint}`:''}`);return data}
async function requestJson(url,payload,timeoutMs=110000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{return await readJsonResponse(await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store',signal:c.signal}))}catch(e){if(e?.name==='AbortError')throw new Error('조사가 너무 오래 걸려 중단됐습니다.');throw e}finally{clearTimeout(t)}}

async function checkHealth(){try{const d=await readJsonResponse(await fetch(`/api/health?t=${Date.now()}`,{cache:'no-store'}));const ok=Boolean(d.groqConnected&&d.tavilyConfigured);$('apiStatus').className=`status ${ok?'ok':'bad'}`;$('apiStatus').innerHTML=`<span class="dot"></span><span>${ok?'Tavily + Groq 정상':'API 확인 필요'}</span>`;$('apiStatus').title=ok?'검색: Tavily · 정리: Groq':(d.error||'연결 실패');return ok}catch(e){$('apiStatus').className='status bad';$('apiStatus').innerHTML='<span class="dot"></span><span>API 오류</span>';return false}}
function diagLine(name,ok,detail=''){return `<div class="diag-row"><b class="${ok?'diag-ok':'diag-bad'}">${ok?'✓':'✕'}</b><span>${escapeHtml(name)}</span><small>${escapeHtml(detail)}</small></div>`}
async function runDiagnostics(){const btn=$('diagBtn'),panel=$('diagPanel');btn.disabled=true;btn.textContent='확인 중';panel.classList.remove('hidden');try{const h=await readJsonResponse(await fetch(`/api/health?t=${Date.now()}`,{cache:'no-store'}));panel.innerHTML=`<div class="diag-head"><strong>${h.groqConnected&&h.tavilyConfigured?'정상':'문제 발견'}</strong><button id="diagClose" class="ghost small">닫기</button></div>${diagLine('Tavily 검색',h.tavilyConfigured,h.tavilyConfigured?'키 설정됨':'TAVILY_API_KEY 필요')}${diagLine('Groq 정리',h.groqConnected,h.groqConnected?'인증 정상':'GROQ_API_KEY 확인')}`;$('diagClose')?.addEventListener('click',()=>panel.classList.add('hidden'))}catch(e){panel.innerHTML=`<strong>진단 실패</strong><p>${escapeHtml(e.message)}</p>`}finally{btn.disabled=false;btn.textContent='진단'}}

function setWorkflow(name){state.workflow=name;$('salesWorkspace').classList.toggle('hidden',name!=='sales');$('deliveryWorkspace').classList.toggle('hidden',name!=='delivery');document.querySelectorAll('.workflow-btn').forEach(b=>b.classList.toggle('active',b.dataset.workflow===name));localStorage.setItem('kpa.workflow',name)}
document.querySelectorAll('.workflow-btn').forEach(b=>b.addEventListener('click',()=>setWorkflow(b.dataset.workflow)));

function setSalesBusy(on){$('salesRunBtn').disabled=on;$('salesRunBtn').querySelector('span').textContent=on?'후보 검색 + 검증 중…':'검증된 해외 고객 찾기';$('salesLoading').classList.toggle('hidden',!on);if(on){$('salesEmpty').classList.add('hidden');$('salesError').classList.add('hidden');$('salesResults').classList.add('hidden')}}
function salesError(msg){$('salesLoading').classList.add('hidden');$('salesResults').classList.add('hidden');$('salesEmpty').classList.add('hidden');$('salesError').textContent=msg;$('salesError').classList.remove('hidden')}
async function runSales(){const focus=$('salesFocus').value.trim();localStorage.setItem('kpa.sales.form',JSON.stringify({focus}));state.salesData=null;setSalesBusy(true);try{if(!await checkHealth())throw new Error('Tavily 또는 Groq 연결을 확인하세요.');const d=await requestJson('/api/discover-clients',{focus});if(!d?.leads?.length)throw new Error('검증을 통과한 후보가 없습니다.');state.salesData=d;localStorage.setItem('kpa.sales.result',JSON.stringify(d));renderSales()}catch(e){salesError(e.message||'고객 발굴에 실패했습니다.')}finally{setSalesBusy(false);if(state.salesData?.leads?.length)$('salesResults').classList.remove('hidden')}}

function evidenceLinks(urls=[]){return `<div class="source-links">${urls.map((u,i)=>safeUrl(u)?`<a href="${escapeHtml(safeUrl(u))}" target="_blank" rel="noopener noreferrer">근거 ${i+1}</a>`:'').join('')}</div>`}
function renderSales(){const d=state.salesData;if(!d)return;$('salesEmpty').classList.add('hidden');$('salesError').classList.add('hidden');$('salesLoading').classList.add('hidden');$('salesResults').classList.remove('hidden');$('salesCsv').disabled=false;const top=d.leads[0];$('salesNext').innerHTML=`<div><span class="eyebadge">지금 할 일</span><strong>${escapeHtml(top.company)}의 실제 의사결정자를 찾고 무료 한국 기업 3곳 샘플을 제안하세요.</strong></div>`;$('salesSummary').innerHTML=`<span><b>${d.leads.length}곳</b> 검증 통과</span><span>공식 홈페이지 확인</span><span>한국 현지 조직 명시 자료 미발견</span>`;$('salesContent').innerHTML=`<div class="candidate-list">${d.leads.map(l=>{const q=l.contact_search_query||`"${l.company}" Founder Head of Sales LinkedIn`;return `<article class="candidate-card"><div class="candidate-top"><div><span class="rank">#${l.rank}</span><h3>${escapeHtml(l.company)}</h3><a class="official-link" href="${escapeHtml(safeUrl(l.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(host(l.url))}</a></div><span class="verified-badge">검증 통과</span></div><div class="verification-row"><span>✓ 공식 홈페이지</span><span>✓ 한국 현지 조직 미확인</span><span>✓ 근거 ${l.source_urls?.length||0}개</span></div><div class="candidate-section"><b>왜 연락하나</b><p>${escapeHtml(l.why_buy_our_service)}</p></div><div class="candidate-section"><b>지금 신호</b><p>${escapeHtml(l.why_now)}</p>${evidenceLinks(l.source_urls)}</div><div class="candidate-section"><b>한국에서 팔아볼 포인트</b><p>${escapeHtml(l.korea_opportunity)}</p></div><div class="contact-line"><div><small>추천 담당자</small><strong>${escapeHtml(l.recommended_role||'Head of Sales')}</strong></div><a href="${escapeHtml(googleSearchUrl(q))}" target="_blank" rel="noopener noreferrer">담당자 찾기</a></div><details class="email-preview"><summary>보낼 첫 메일 보기</summary><p>${escapeHtml(l.outreach_en)}</p><button class="copy-mail" data-rank="${l.rank}">영업문 복사</button></details><div class="candidate-actions"><a class="primary-link" href="${escapeHtml(googleSearchUrl(q))}" target="_blank" rel="noopener noreferrer">1. 담당자 찾기</a><button class="copy-mail" data-rank="${l.rank}">2. 메일 복사</button><a href="${escapeHtml(safeUrl(l.url))}" target="_blank" rel="noopener noreferrer">홈페이지 확인</a></div></article>`}).join('')}</div>`;document.querySelectorAll('.copy-mail').forEach(btn=>btn.addEventListener('click',()=>{const l=d.leads.find(x=>x.rank===Number(btn.dataset.rank));copyText(l?.outreach_en||'',btn)}))}
function exportSalesCsv(){const d=state.salesData;if(!d)return;const cols=['rank','company','url','fit_score','why_buy_our_service','why_now','source_urls','recommended_role','contact_search_query','korea_opportunity','verification_status','outreach_en'];const rows=[cols.join(','),...d.leads.map(l=>cols.map(c=>csvCell(l[c])).join(','))];download(`korea-sales-leads-${Date.now()}.csv`,'text/csv;charset=utf-8','\ufeff'+rows.join('\n'))}

const deliveryFields=['clientUrl','productHint','targetNotes','seeds'];
function saveDeliveryForm(){const v={};deliveryFields.forEach(id=>v[id]=$(id).value);localStorage.setItem('kpa.delivery.form',JSON.stringify(v))}
function setDeliveryBusy(on){$('runBtn').disabled=on;$('runBtn').querySelector('span').textContent=on?'한국 시장 조사 중…':'한국 영업 후보 만들기';$('loadingState').classList.toggle('hidden',!on);if(on){$('emptyState').classList.add('hidden');$('errorState').classList.add('hidden');$('results').classList.add('hidden')}}
function showDeliveryError(msg){$('loadingState').classList.add('hidden');$('emptyState').classList.add('hidden');$('results').classList.add('hidden');$('errorState').textContent=msg;$('errorState').classList.remove('hidden')}
async function runDelivery(){const clientUrl=$('clientUrl').value.trim();if(!clientUrl){showDeliveryError('고객 SaaS URL을 입력하세요.');return}saveDeliveryForm();setDeliveryBusy(true);try{if(!await checkHealth())throw new Error('API 연결을 확인하세요.');const d=await requestJson('/api/analyze',{clientUrl,productHint:$('productHint').value,targetNotes:$('targetNotes').value,seeds:$('seeds').value,count:3});state.deliveryData=d;state.deliveryTab='prospects';localStorage.setItem('kpa.delivery.result',JSON.stringify(d));renderDelivery()}catch(e){state.deliveryData=null;showDeliveryError(e.message||'분석에 실패했습니다.')}finally{setDeliveryBusy(false);if(state.deliveryData)$('results').classList.remove('hidden')}}
function metric(label,value){return `<div class="metric"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value||'-')}</strong></div>`}
function renderDelivery(){const d=state.deliveryData;if(!d)return;$('emptyState').classList.add('hidden');$('loadingState').classList.add('hidden');$('errorState').classList.add('hidden');$('results').classList.remove('hidden');$('exportCsv').disabled=false;const top=d.prospects?.[0];$('summaryGrid').innerHTML=metric('고객',d.client?.name||host(d.client?.url))+metric('한국 후보',`${d.prospects?.length||0}곳`)+metric('1위 점수',top?`${top.fit_score}/100`:'-');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.deliveryTab));renderDeliveryTab()}
function renderDeliveryTab(){const d=state.deliveryData;if(!d)return;const root=$('tabContent');if(state.deliveryTab==='prospects'){root.innerHTML=`<div style="overflow:auto"><table class="prospect-table"><thead><tr><th>#</th><th>기업</th><th>점수</th><th>적합 이유</th><th>구매 신호</th><th>근거</th></tr></thead><tbody>${(d.prospects||[]).map(p=>`<tr><td>${p.rank}</td><td class="company-cell"><strong>${escapeHtml(p.company)}</strong>${safeUrl(p.url)?`<a target="_blank" rel="noopener noreferrer" href="${escapeHtml(safeUrl(p.url))}">${escapeHtml(host(p.url))}</a>`:''}</td><td><span class="score">${p.fit_score}</span></td><td>${escapeHtml(p.why_fit)}</td><td>${escapeHtml(p.buying_signal)}</td><td>${evidenceLinks(p.source_urls)}</td></tr>`).join('')}</tbody></table></div>`}else if(state.deliveryTab==='contacts'){root.innerHTML=`<div class="cards">${(d.prospects||[]).map(p=>{const q=p.contact_search_query||`${p.company} ${p.recommended_role||'Head'} LinkedIn`;return `<article class="contact-card"><div class="top"><div><span class="rank">#${p.rank} · ${escapeHtml(p.company)}</span><h3>${escapeHtml(p.recommended_role||'담당 직책 확인 필요')}</h3></div><a class="ghost small" href="${escapeHtml(googleSearchUrl(q))}" target="_blank" rel="noopener noreferrer">검색</a></div><p>${escapeHtml(q)}</p></article>`}).join('')}</div>`}else if(state.deliveryTab==='messages'){root.innerHTML=`<div class="cards">${(d.prospects||[]).map(p=>`<article class="message-card"><div class="top"><div><span class="rank">#${p.rank}</span><h3>${escapeHtml(p.company)}</h3></div><button class="copy delivery-copy" data-rank="${p.rank}">복사</button></div><p class="message-text">${escapeHtml(p.message_ko||p.message_en)}</p></article>`).join('')}</div>`;root.querySelectorAll('.delivery-copy').forEach(btn=>btn.addEventListener('click',()=>{const p=d.prospects.find(x=>x.rank===Number(btn.dataset.rank));copyText(p?.message_ko||p?.message_en||'',btn)}))}else{const s=d.strategy||{};root.innerHTML=`<div class="action-steps"><div class="action-step"><b>1</b><div><strong>상위 후보 근거 확인</strong><span>${escapeHtml(s.first_segment||'점수가 높은 기업부터 확인합니다.')}</span></div></div><div class="action-step"><b>2</b><div><strong>CSV 납품</strong><span>${escapeHtml(s.core_offer||'한국 후보와 메시지를 고객에게 전달합니다.')}</span></div></div><div class="action-step"><b>3</b><div><strong>운영 계약 제안</strong><span>${escapeHtml(s.next_action||'반응 데이터를 바탕으로 월 운영을 제안합니다.')}</span></div></div></div>`}}
function exportDeliveryCsv(){const d=state.deliveryData;if(!d)return;const cols=['rank','company','url','industry','fit_score','why_fit','buying_signal','source_urls','recommended_role','contact_search_query','sales_angle','message_ko','message_en'];const rows=[cols.join(','),...(d.prospects||[]).map(p=>cols.map(c=>csvCell(p[c])).join(','))];download(`korea-prospect-pack-${Date.now()}.csv`,'text/csv;charset=utf-8','\ufeff'+rows.join('\n'))}

$('diagBtn').addEventListener('click',runDiagnostics);
$('salesRunBtn').addEventListener('click',runSales);
$('salesCsv').addEventListener('click',exportSalesCsv);
$('salesDemo').addEventListener('click',()=>{$('salesFocus').value='Seed~Series B B2B SaaS/AI. 최근 APAC·일본·싱가포르·호주 확장 신호가 있고 아직 한국 현지 영업조직이 강하지 않은 회사.'});
$('runBtn').addEventListener('click',runDelivery);
$('exportCsv').addEventListener('click',exportDeliveryCsv);
$('fillDemo').addEventListener('click',()=>{$('clientUrl').value='https://www.intercom.com';$('productHint').value='AI 고객지원 자동화 SaaS';$('targetNotes').value='한국 이커머스 중 고객 문의량이 많거나 CS 채용이 늘어난 회사';saveDeliveryForm()});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.deliveryTab=b.dataset.tab;renderDelivery()}));
deliveryFields.forEach(id=>$(id).addEventListener('change',saveDeliveryForm));
try{const f=JSON.parse(localStorage.getItem('kpa.sales.form')||'{}');if(f.focus!=null)$('salesFocus').value=f.focus}catch{}
try{const f=JSON.parse(localStorage.getItem('kpa.delivery.form')||'{}');deliveryFields.forEach(id=>{if(f[id]!=null)$(id).value=f[id]})}catch{}
try{const d=JSON.parse(localStorage.getItem('kpa.sales.result')||'null');if(d?.leads?.length){state.salesData=d;renderSales()}}catch{}
try{const d=JSON.parse(localStorage.getItem('kpa.delivery.result')||'null');if(d?.prospects?.length){state.deliveryData=d;renderDelivery()}}catch{}
setWorkflow(localStorage.getItem('kpa.workflow')==='delivery'?'delivery':'sales');
checkHealth();
