const GROQ_CHAT_URL='https://api.groq.com/openai/v1/chat/completions';
const SEARCH_MODEL='openai/gpt-oss-20b';
const STRUCTURE_MODEL='openai/gpt-oss-120b';
function clean(v,max=1400){return typeof v==='string'?v.trim().slice(0,max):''}
function safeError(v=''){return String(v).replace(/gsk_[A-Za-z0-9_-]+/g,'[redacted]').slice(0,700)}
function rateInfo(r){return{remaining_requests:r.headers.get('x-ratelimit-remaining-requests'),remaining_tokens:r.headers.get('x-ratelimit-remaining-tokens'),retry_after:r.headers.get('retry-after')}}
function validUrls(v,limit=4){return Array.isArray(v)?v.map(String).filter(x=>/^https?:\/\//i.test(x)).slice(0,limit):[]}
async function fetchWithTimeout(url,options,timeoutMs){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs),started=Date.now();try{const response=await fetch(url,{...options,signal:c.signal});return{response,durationMs:Date.now()-started}}catch(e){if(e?.name==='AbortError'){const x=new Error(`Groq search timed out after ${Math.round(timeoutMs/1000)}s`);x.status=504;throw x}throw e}finally{clearTimeout(t)}}
function extractSearchResults(payload){const message=payload?.choices?.[0]?.message||{},out=[];function walk(node){if(!node)return;if(Array.isArray(node)){node.forEach(walk);return}if(typeof node!=='object')return;const url=clean(node.url,500);if(/^https?:\/\//i.test(url))out.push({title:clean(node.title||node.name,240),url,content:clean(node.content||node.snippet||node.text,650),score:Number(node.score)||0});Object.values(node).forEach(walk)}walk(message.executed_tools);walk(message.annotations);const content=String(message.content||'');for(const m of content.matchAll(/https?:\/\/[^\s)\]}>,"']+/g))out.push({title:'',url:m[0],content:'',score:0});const seen=new Set();return out.filter(r=>{if(seen.has(r.url))return false;seen.add(r.url);return true}).slice(0,12)}
function evidenceFromPayload(payload,sources){const message=payload?.choices?.[0]?.message||{},parts=[];sources.forEach((s,i)=>parts.push(`SOURCE ${i+1}\nTITLE: ${s.title}\nURL: ${s.url}\nSNIPPET: ${s.content}`));if(message.content)parts.push(`BROWSER RESULT:\n${clean(String(message.content),2200)}`);return parts.join('\n\n').slice(0,6200)}
async function searchBuyers({focus}){const prompt=`Use browser search now. Find exactly 3 overseas B2B SaaS/AI companies that could buy a small Korea market-entry sales pilot. Preference: ${focus||'Seed-Series B; recent APAC/Japan/Singapore/global expansion, funding, or sales/partnership hiring; clear Korea B2B use case; no mature Korea sales team.'} Use recent public evidence, avoid giant companies, and keep the response short. For EACH company explicitly print: COMPANY, OFFICIAL_URL, TRIGGER, SOURCE_URL. SOURCE_URL must be the full URL of evidence you actually found.`;const{response,durationMs}=await fetchWithTimeout(GROQ_CHAT_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:SEARCH_MODEL,messages:[{role:'user',content:prompt}],temperature:0.2,reasoning_effort:'low',reasoning_format:'hidden',max_completion_tokens:1200,tool_choice:'required',tools:[{type:'browser_search'}]})},30000);const raw=await response.text();if(!response.ok){let d=raw;try{d=JSON.parse(raw)?.error?.message||raw}catch{}const e=new Error(`Groq browser search HTTP ${response.status}: ${safeError(d)}`);e.status=response.status;e.retryAfter=response.headers.get('retry-after');e.rate=rateInfo(response);throw e}const payload=JSON.parse(raw),sources=extractSearchResults(payload),evidence=evidenceFromPayload(payload,sources);if(!evidence.trim())throw new Error('Browser search returned no evidence');return{evidence,sources,meta:{model:SEARCH_MODEL,duration_ms:durationMs,search_results:sources.length,usage:payload?.usage||null,rate:rateInfo(response)}}}
const leadSchema={type:'object',properties:{company:{type:'string'},url:{type:'string'},country:{type:'string'},fit_score:{type:'integer'},why_buy_our_service:{type:'string'},why_now:{type:'string'},source_urls:{type:'array',items:{type:'string'}},recommended_role:{type:'string'},contact_search_query:{type:'string'},korea_opportunity:{type:'string'},outreach_en:{type:'string'},outreach_ko:{type:'string'}},required:['company','url','country','fit_score','why_buy_our_service','why_now','source_urls','recommended_role','contact_search_query','korea_opportunity','outreach_en','outreach_ko'],additionalProperties:false};
const resultSchema={type:'object',properties:{leads:{type:'array',items:leadSchema},next_action:{type:'string'}},required:['leads','next_action'],additionalProperties:false};
async function structureEvidence({evidence,focus}){const prompt=`아래 브라우저 검색 근거만 사용해 연락할 해외 SaaS 후보 최대 3곳을 정리한다. 조건: ${focus||'최근 확장 신호 + 한국 B2B 사용처'}. 상품은 390,000원 Korea Pipeline Pilot. 설명은 한국어. URL은 근거의 URL만 그대로 복사한다. 확인 안 된 사실 금지. 근거 1개면 70점 초과 금지. outreach_en은 50~70단어, 링크 없이 샘플을 보내도 되는지 묻고 끝낸다.\n\n${evidence.slice(0,6200)}`;const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const response=await fetch(GROQ_CHAT_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:STRUCTURE_MODEL,messages:[{role:'user',content:prompt}],temperature:0,reasoning_effort:'low',reasoning_format:'hidden',max_completion_tokens:1500,response_format:{type:'json_schema',json_schema:{name:'korea_buyer_leads',strict:true,schema:resultSchema}}}),signal:c.signal});const raw=await response.text();if(!response.ok){let d=raw;try{d=JSON.parse(raw)?.error?.message||raw}catch{}const e=new Error(`Groq structure HTTP ${response.status}: ${safeError(d)}`);e.status=response.status;e.retryAfter=response.headers.get('retry-after');e.rate=rateInfo(response);throw e}const payload=JSON.parse(raw),content=payload?.choices?.[0]?.message?.content;if(!content)throw new Error('Groq structure returned empty content');return{data:JSON.parse(content),model:STRUCTURE_MODEL,usage:payload?.usage||null}}catch(e){if(e?.name==='AbortError'){const x=new Error('Groq structure timed out');x.status=504;throw x}throw e}finally{clearTimeout(t)}}
function matchingEvidence(company,sources){const n=clean(company,140).toLowerCase();return n?sources.filter(s=>`${s.title} ${s.content}`.toLowerCase().includes(n)).map(s=>s.url).slice(0,2):[]}
function sanitizeLead(lead,sources){let source_urls=validUrls(lead?.source_urls);if(!source_urls.length)source_urls=matchingEvidence(lead?.company,sources);let score=Math.max(0,Math.min(100,Number.parseInt(lead?.fit_score,10)||0));if(!source_urls.length)score=Math.min(score,40);if(source_urls.length===1)score=Math.min(score,70);return{company:clean(lead?.company,140),url:clean(lead?.url,350),country:clean(lead?.country,80),category:'',fit_score:score,why_buy_our_service:clean(lead?.why_buy_our_service,420),why_now:clean(lead?.why_now,420),source_urls,recommended_role:clean(lead?.recommended_role,100),contact_search_query:clean(lead?.contact_search_query,220),korea_opportunity:clean(lead?.korea_opportunity,420),outreach_en:clean(lead?.outreach_en,900),outreach_ko:clean(lead?.outreach_ko,900),confidence:source_urls.length>=2?'high':'medium',warning:''}}
export async function POST(request){if(!process.env.GROQ_API_KEY)return Response.json({error:'GROQ_API_KEY가 Vercel 환경변수에 없습니다.'},{status:503});let body={};try{body=await request.json()}catch{return Response.json({error:'요청 형식이 잘못됐습니다.'},{status:400})}const focus=clean(body.focus,1000);let search;try{search=await searchBuyers({focus})}catch(e){return Response.json({error:safeError(e?.message||e),hint:e?.status===429?`검색 모델 사용량 한도입니다. ${e.retryAfter||'잠시'} 후 다시 실행하세요.`:'웹 검색에 실패했습니다.',phase:'search',rate:e?.rate||null},{status:e?.status||502})}try{const structured=await structureEvidence({evidence:search.evidence,focus});const leads=(Array.isArray(structured.data?.leads)?structured.data.leads:[]).map(l=>sanitizeLead(l,search.sources)).filter(l=>l.company&&/^https?:\/\//i.test(l.url)&&l.source_urls.length).slice(0,3).sort((a,b)=>b.fit_score-a.fit_score).map((l,i)=>({...l,rank:i+1}));if(!leads.length)return Response.json({error:'검색은 됐지만 근거 URL이 있는 후보를 만들지 못했습니다.',hint:'다시 실행하면 검색 결과를 새로 가져옵니다.',phase:'validation',meta:{search_results:search.sources.length}},{status:422});return Response.json({leads,strategy:{best_segment:'',pitch:'',next_action:clean(structured.data?.next_action,400)},meta:{search:search.meta,structure_model:structured.model,structure_usage:structured.usage,returned_count:leads.length,pipeline:'20b-browser-search -> 120b-strict-structure'}},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({error:safeError(e?.message||e),hint:e?.status===429?`정리 모델 사용량 한도입니다. ${e.retryAfter||'잠시'} 후 다시 실행하세요.`:'검색은 성공했지만 정리 단계에서 실패했습니다.',phase:'structure',rate:e?.rate||null},{status:e?.status||502})}}
