import { tavilyConfigured, tavilySearch, tavilySearchMany, formatEvidence } from '../lib/web-search.js';

const GROQ_CHAT_URL='https://api.groq.com/openai/v1/chat/completions';
const STRUCTURE_MODEL='openai/gpt-oss-120b';
const DISCOVERY_EXCLUDES=['instagram.com','facebook.com','x.com','twitter.com','youtube.com','reddit.com','pinterest.com','medium.com','crunchbase.com','glassdoor.com','quora.com','internations.org','visible.vc','wikipedia.org'];
const COMPANY_URL_BLOCKLIST=[...DISCOVERY_EXCLUDES,'linkedin.com','techcrunch.com','reuters.com','prnewswire.com','businesswire.com','forbes.com','bloomberg.com','yahoo.com'];
const MATURE_COMPANIES=['fiverr','airwallex','canva','anthropic','openai','cohere','stripe','shopify','salesforce','hubspot','atlassian','microsoft','google','amazon','aws','oracle','adobe','zoom','slack','notion','intercom'];
const TRIGGER=/(series\s+[ab]|seed|funding|raised|raises|investment|expand|expansion|launch|hiring|hire|sales|partnership|international|apac|asia|japan|singapore|australia|global)/i;

function clean(v,max=1400){return typeof v==='string'?v.trim().slice(0,max):''}
function safeError(v=''){return String(v).replace(/gsk_[A-Za-z0-9_-]+/g,'[redacted]').replace(/tvly-[A-Za-z0-9_-]+/g,'[redacted]').slice(0,700)}
function hostname(v=''){try{return new URL(v).hostname.toLowerCase().replace(/^www\./,'')}catch{return''}}
function rootHost(v=''){const h=hostname(v),p=h.split('.');return p.length>2?p.slice(-2).join('.'):h}
function token(v=''){return String(v).toLowerCase().replace(/[^a-z0-9]/g,'')}
function blockedCompanyUrl(url){const h=rootHost(url);return !h||COMPANY_URL_BLOCKLIST.some(x=>h===x||h.endsWith(`.${x}`))}
function looksLikeCompanyHost(url,company){if(!url||blockedCompanyUrl(url))return false;const h=token(rootHost(url).split('.')[0]),c=token(company);return h.length>=2&&c.length>=2&&(c.includes(h)||h.includes(c.slice(0,Math.min(c.length,10))))}
function matureCompany(company=''){const c=token(company);return MATURE_COMPANIES.some(x=>c===token(x)||c.startsWith(token(x)))}
function companyMentioned(row,company){const c=token(company);if(c.length<3)return false;return token(`${row?.title||''} ${row?.content||''}`).includes(c)}
function candidateEvidence(company,sources){return sources.filter(r=>companyMentioned(r,company)&&TRIGGER.test(`${r.title} ${r.content}`)).slice(0,3)}
function dedupe(arr){return[...new Set(arr.filter(Boolean))]}

async function discoverEvidence(focus){if(!tavilyConfigured())throw new Error('TAVILY_API_KEY가 필요합니다.');const f=clean(focus,600);const queries=f?[`${f} APAC expansion funding 2026 SaaS startup`,`${f} Japan Singapore Australia expansion 2026`,`${f} Series A Series B international growth 2026`]:['B2B SaaS startup APAC expansion Series A 2026','AI SaaS startup Japan Singapore expansion funding 2026','B2B software Series B international expansion Asia 2026'];const r=await tavilySearchMany(queries,{maxResults:10,timeRange:'year',excludeDomains:DISCOVERY_EXCLUDES,topic:'news'});const sources=r.results.slice(0,26);if(!sources.length)throw new Error('Tavily에서 최신 후보 근거를 찾지 못했습니다.');return{evidence:formatEvidence(sources,26,10000),sources,meta:{...r.meta,search_results:sources.length}}}

const schema={type:'object',properties:{candidates:{type:'array',items:{type:'object',properties:{company:{type:'string'},official_url_hint:{type:'string'},source_urls:{type:'array',items:{type:'string'}},recommended_role:{type:'string'}},required:['company','official_url_hint','source_urls','recommended_role'],additionalProperties:false}}},required:['candidates'],additionalProperties:false};

async function shortlist(evidence,focus){const prompt=`아래 SOURCE만 보고 한국 시장 테스트 서비스를 제안할 해외 B2B SaaS/AI 후보를 최대 8곳 추린다.\n조건: ${clean(focus,600)||'소·중형 B2B SaaS/AI, 최근 APAC·일본·싱가포르·호주·글로벌 확장/투자/영업채용 신호가 있는 회사.'}\n절대 규칙:\n1) 후보 회사명은 SOURCE 제목 또는 본문에 실제로 직접 등장해야 한다.\n2) 그 회사를 직접 언급한 SOURCE 안에 투자·확장·출시·채용·파트너십 등 최신 신호가 있어야 한다.\n3) 한국 회사, 초대형/성숙 글로벌 플랫폼, 이미 한국 사업이 성숙한 회사는 제외한다.\n4) official_url_hint는 SOURCE에 공식 홈페이지가 명확할 때만 넣고 아니면 빈 문자열.\n5) source_urls는 그 회사가 직접 언급된 SOURCE URL만 넣는다. 일반 시장 글이나 VC 목록 URL을 회사 근거로 쓰지 않는다.\n6) recommended_role은 Founder, CEO, Head of Sales, BD, Partnerships, Growth 중 하나.\n7) 설명이나 점수는 만들지 말고 가장 적합한 순서대로만 배열한다.\n\n${evidence.slice(0,10000)}`;const c=new AbortController(),t=setTimeout(()=>c.abort(),22000);try{const response=await fetch(GROQ_CHAT_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:STRUCTURE_MODEL,messages:[{role:'user',content:prompt}],temperature:0,reasoning_effort:'low',reasoning_format:'hidden',max_completion_tokens:1200,response_format:{type:'json_schema',json_schema:{name:'candidate_names',strict:true,schema}}}),signal:c.signal});const raw=await response.text();if(!response.ok){let d=raw;try{d=JSON.parse(raw)?.error?.message||raw}catch{}const e=new Error(`Groq HTTP ${response.status}: ${safeError(d)}`);e.status=response.status;throw e}const payload=JSON.parse(raw),content=payload?.choices?.[0]?.message?.content;if(!content)throw new Error('Groq가 후보를 반환하지 않았습니다.');return{data:JSON.parse(content),usage:payload?.usage||null}}catch(e){if(e?.name==='AbortError'){const x=new Error('후보 정리가 시간 초과되었습니다.');x.status=504;throw x}throw e}finally{clearTimeout(t)}}

function explicitKoreaPresence(text=''){const s=String(text).toLowerCase();return[/korea\s+(office|team|country manager|general manager|head|sales team|subsidiary|operations)/,/(office|team|subsidiary|operations)\s+(in|for)\s+(south\s+)?korea/,/seoul\s+(office|team|hub|based|role|roles|jobs|location)/,/(country manager|head of|general manager)[^.!?]{0,40}(korea|seoul)/,/(launch|launched|launching|operate|operating|operations)[^.!?]{0,40}(in\s+)?(south\s+)?korea/,/(acquire|acquired|acquisition)[^.!?]{0,80}(korea|korean)/,/(korea|korean)[^.!?]{0,50}(subsidiary|entity|license|office|team)/].some(r=>r.test(s))}
function pickOfficialUrl(company,hint,rows){if(looksLikeCompanyHost(hint,company))return`https://${rootHost(hint)}/`;const hit=rows.find(r=>looksLikeCompanyHost(r.url,company));return hit?`https://${rootHost(hit.url)}/`:''}

async function verifyCandidate(candidate,discoverySources,index){const company=clean(candidate?.company,120);if(!company||matureCompany(company))return null;const matched=candidateEvidence(company,discoverySources);if(!matched.length)return null;const r=await tavilySearch(`"${company}" official website Korea office Seoul country manager Korea team careers`,{maxResults:9,timeRange:null,excludeDomains:['instagram.com','facebook.com','x.com','twitter.com','youtube.com','reddit.com','pinterest.com'],topic:'general'});const rows=r.results||[],officialUrl=pickOfficialUrl(company,candidate?.official_url_hint,rows);if(!officialUrl)return null;const koreaRows=rows.filter(row=>/korea|seoul|한국|서울/i.test(`${row.title} ${row.content} ${row.url}`));if(koreaRows.some(row=>explicitKoreaPresence(`${row.title} ${row.content}`)))return null;const sourceUrls=dedupe(matched.map(x=>x.url)).slice(0,3);if(!sourceUrls.length)return null;const role=clean(candidate?.recommended_role,80)||'Head of Sales';return{company,url:officialUrl,fit_score:Math.max(65,85-index*5),why_buy_our_service:`${company}는 최근 해외 확장 관련 공개 신호가 직접 확인됐고, 이번 검색에서는 한국 현지 영업조직이 확인되지 않아 현지 채용 전에 한국 시장을 작게 검증해 볼 후보입니다.`,why_now:'최근 1년 내 회사명이 직접 언급된 투자·확장·출시·영업 관련 공개 자료가 확인됐습니다. 아래 근거를 확인한 뒤 연락합니다.',korea_opportunity:`무료 샘플에서는 ${company}의 제품을 살 가능성이 있는 한국 기업 3곳과 각 기업에 연락할 이유를 먼저 제시합니다.`,source_urls:sourceUrls,signal_title:clean(matched[0]?.title,220),recommended_role:role,contact_search_query:`"${company}" (Founder OR CEO OR "Head of Sales" OR Partnerships OR Growth) LinkedIn`,verification_status:'한국 현지 조직 명시 자료 미발견',verification_note:'공식 홈페이지 확인 · 한국 오피스/현지팀 명시 자료 미발견',outreach_en:`Hi — I came across ${company} while researching B2B SaaS teams expanding internationally. I help teams test Korea before hiring locally by mapping 3 Korean accounts and why each may be worth contacting. I can send you a free 3-account sample for ${company}. Would that be useful?`,outreach_ko:`안녕하세요. 해외 확장 중인 B2B SaaS를 조사하다 ${company}를 보게 됐습니다. 한국에서 현지 직원을 채용하기 전에 잠재고객과 접촉 이유를 작게 검증하는 일을 하고 있습니다. ${company}에 맞는 한국 기업 3곳 샘플을 무료로 보내드려도 될까요?`}}

export async function POST(request){if(!process.env.GROQ_API_KEY)return Response.json({error:'GROQ_API_KEY가 없습니다.'},{status:503});if(!tavilyConfigured())return Response.json({error:'TAVILY_API_KEY가 없습니다.'},{status:503});let body={};try{body=await request.json()}catch{return Response.json({error:'요청 형식이 잘못됐습니다.'},{status:400})}const focus=clean(body.focus,600);try{const discovery=await discoverEvidence(focus),short=await shortlist(discovery.evidence,focus),candidates=Array.isArray(short.data?.candidates)?short.data.candidates.slice(0,8):[];if(!candidates.length)return Response.json({error:'최신 근거가 있는 후보를 찾지 못했습니다.'},{status:422});const verified=[];for(let i=0;i<candidates.length;i++){try{const v=await verifyCandidate(candidates[i],discovery.sources,i);if(v)verified.push(v)}catch{}if(verified.length>=3)break}const leads=verified.slice(0,3).map((x,i)=>({...x,rank:i+1}));if(!leads.length)return Response.json({error:'공식 홈페이지·최신 회사별 근거·한국 조직 검증을 모두 통과한 후보가 없었습니다.',hint:'다른 고객군으로 다시 실행하세요.'},{status:422});return Response.json({leads,strategy:{next_action:'1위 회사의 실제 의사결정자를 확인하고 무료 한국 기업 3곳 샘플을 제안하는 첫 메일을 보냅니다.'},meta:{search:discovery.meta,structure_model:STRUCTURE_MODEL,structure_usage:short.usage,returned_count:leads.length,pipeline:'Tavily 뉴스 검색 → Groq 회사명 선별 → 회사별 근거 매칭 → 공식URL/한국조직 재검증'}},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({error:safeError(e?.message||e),hint:e?.status===429?'API 사용량 제한입니다. 잠시 후 다시 시도하세요.':'후보 발굴 과정에서 오류가 발생했습니다.'},{status:e?.status||502})}}
